### ISSUE TITLE
ValueError on migrate group.0006

### ISSUE THREAD

**Issue by whs** [whsatku/social#42]
While running `python manage.py migrate` on 6aea58fb7898c88190e42c328d71ad304dc4b297

```
  Applying group.0006_auto_20151005_2202...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 275, in database_forwards
    to_model._meta.get_field(self.new_name),
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 566, in _alter_field
    old_default = self.effective_default(old_field)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 211, in effective_default
    default = field.get_db_prep_save(default, self.connection)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1951, in get_db_prep_save
    return self.related_field.get_db_prep_save(value, connection=connection)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 710, in get_db_prep_save
    prepared=False)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 978, in get_db_prep_value
    value = connection.ops.validate_autopk_value(value)
  File "/var/www/virtual/whs.in.th/social/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/operations.py", line 137, in validate_autopk_value
    raise ValueError('The database backend does not accept 0 as a '
ValueError: The database backend does not accept 0 as a value for AutoField.
```

**Comment by whs** [comment]
This probably can be fixed by removing `default=0` from all `ForeignKey` in `group` and `newsfeed` module.

The offending migrations are
- `group/migrations/0003_auto_20150921_1425.py`
- `newsfeed/migrations/0003_auto_20151003_0237.py`

**Comment by whs** [comment]
Fixed in staging
